Repository antvis/site, pull requests merged in 2019-10, with the labels that each got.

#207 add: layout demos; add: case demos; fix: original demo problems; fix:…
  site-config.js
  site/zh-cn/g6/3.x/data.js
  site/zh-cn/g6/3.x/demo/case/american-migration-bundling.html
  site/zh-cn/g6/3.x/demo/case/beijing-metro-animation.html
  site/zh-cn/g6/3.x/demo/case/cluster-simplify.html
  site/zh-cn/g6/3.x/demo/case/voucher-transfer.html
  site/zh-cn/g6/3.x/demo/graphql/layout-bubbles.html
  site/zh-cn/g6/3.x/demo/graphql/layout-circular-config-translation.html
  site/zh-cn/g6/3.x/demo/graphql/layout-custom-bigraph.html
  site/zh-cn/g6/3.x/demo/graphql/layout-dagre-config-translation.html
  site/zh-cn/g6/3.x/demo/graphql/layout-data-translation.html
  site/zh-cn/g6/3.x/demo/graphql/layout-force-expand.html
  site/zh-cn/g6/3.x/demo/graphql/layout-fruchterman-config-translation.html
  site/zh-cn/g6/3.x/demo/graphql/layout-radial-config-translation.html
  site/zh-cn/g6/3.x/demo/graphql/layout-radial-expand.html
  site/zh-cn/g6/3.x/demo/graphql/layout-subgraph.html
  site/zh-cn/g6/3.x/demo/graphql/layout-timing.html
  site/zh-cn/g6/3.x/demo/graphql/layout-tree-bubbles.html
  site/zh-cn/g6/3.x/demo/net/arc-diagram.html
  site/zh-cn/g6/3.x/demo/net/circular-arc-diagram.html
  site/zh-cn/g6/3.x/demo/shape/area-chart-node.html
  site/zh-cn/g6/3.x/demo/shape/bar-chart-node.html
  site/zh-cn/g6/3.x/demo/shape/line-chart-node.html
  site/zh-cn/g6/3.x/demo/shape/point-chart-node.html
  site/zh-cn/g6/3.x/demo/shape/polyline.html
  site/zh-cn/g6/3.x/demo/shape/register-arrow.html
  site/zh-cn/g6/3.x/demo/shape/register-polyline.html
  site/zh-cn/g6/3.x/demo/shape/stacked-bar-chart-node.html
  site/zh-cn/g6/3.x/demo/star/cubic-horiontal.html
  site/zh-cn/g6/3.x/demo/star/default-shapes.html
  site/zh-cn/g6/3.x/demo/star/multiple-edge-label.html
  site/zh-cn/g6/3.x/demo/star/multiple-node-lable.html
  site/zh-cn/g6/3.x/demo/tool/context-menu.html
  site/zh-cn/g6/3.x/demo/tool/focus-center.html
  site/zh-cn/g6/3.x/demo/tool/grid.html
  site/zh-cn/g6/3.x/demo/tool/minimap.html
  site/zh-cn/g6/3.x/demo/tool/sub-event.html
  site/zh-cn/g6/3.x/demo/tool/tooltip.html
  theme/default/templates/demos.html
  theme/default/templates/layout.html
  theme/default/templates/macro/demo.html
Labels: PR: reviewed-changes-requested, add

#208 fix: fix the header and left menu in demos page of all the products
  theme/default/src/demos.js
  theme/default/templates/demos.html
Labels: PR: reviewed-changes-requested, bug

#209 fix: nodeStyle and edgeStyle problems; add: notes; fix: force layout …
  site/zh-cn/g6/3.x/demo/case/american-migration-bundling.html
  site/zh-cn/g6/3.x/demo/case/beijing-metro-animation.html
  site/zh-cn/g6/3.x/demo/case/cluster-simplify.html
  site/zh-cn/g6/3.x/demo/case/voucher-transfer.html
  site/zh-cn/g6/3.x/demo/flow/sankey.html
  site/zh-cn/g6/3.x/demo/graphql/layout-bubbles.html
  site/zh-cn/g6/3.x/demo/graphql/layout-circular-config-translation.html
  site/zh-cn/g6/3.x/demo/graphql/layout-custom-bigraph.html
  site/zh-cn/g6/3.x/demo/graphql/layout-dagre-config-translation.html
  site/zh-cn/g6/3.x/demo/graphql/layout-data-translation.html
  site/zh-cn/g6/3.x/demo/graphql/layout-force-expand.html
  site/zh-cn/g6/3.x/demo/graphql/layout-fruchterman-config-translation.html
  site/zh-cn/g6/3.x/demo/graphql/layout-radial-config-translation.html
  site/zh-cn/g6/3.x/demo/graphql/layout-radial-expand.html
  site/zh-cn/g6/3.x/demo/graphql/layout-subgraph.html
  site/zh-cn/g6/3.x/demo/graphql/layout-timing.html
  site/zh-cn/g6/3.x/demo/graphql/layout-tree-bubbles.html
  site/zh-cn/g6/3.x/demo/net/base-force.html
  site/zh-cn/g6/3.x/demo/net/interactive-force.html
  site/zh-cn/g6/3.x/demo/tree/radial-tree.html
  site/zh-cn/g6/3.x/demo/tree/tree-compact-box.html
  site/zh-cn/g6/3.x/demo/tree/tree-dendrogram.html
  site/zh-cn/g6/3.x/demo/tree/tree-edge-label.html
  site/zh-cn/g6/3.x/demo/tree/tree-mindmap.html
Labels: PR: unreviewed, bug

#210 fix: g6 force demo use inner layout
  site/zh-cn/g6/3.x/demo/net/arc-diagram.html
  site/zh-cn/g6/3.x/demo/net/base-force.html
  site/zh-cn/g6/3.x/demo/net/interactive-force.html
Labels: PR: unreviewed, bug

#211 fix: demos page bug; add: g6 edge bundling demo; fix: g6 demos catego…
  site/zh-cn/g6/3.x/data.js
  site/zh-cn/g6/3.x/demo/graphql/arc-diagram.html
  site/zh-cn/g6/3.x/demo/graphql/circular-arc-diagram.html
  site/zh-cn/g6/3.x/demo/graphql/sankey.html
  site/zh-cn/g6/3.x/demo/interaction/interactive-force.html
  site/zh-cn/g6/3.x/demo/interaction/layout-force-expand.html
  site/zh-cn/g6/3.x/demo/net/base-force.html
  site/zh-cn/g6/3.x/demo/net/dagre.html
  site/zh-cn/g6/3.x/demo/net/er-diagram.html
  site/zh-cn/g6/3.x/demo/net/layout-circular-config-translation.html
  site/zh-cn/g6/3.x/demo/net/layout-custom-bigraph.html
  site/zh-cn/g6/3.x/demo/net/layout-dagre-config-translation.html
  site/zh-cn/g6/3.x/demo/net/layout-data-translation.html
  site/zh-cn/g6/3.x/demo/net/layout-fruchterman-config-translation.html
  site/zh-cn/g6/3.x/demo/net/layout-radial-config-translation.html
  site/zh-cn/g6/3.x/demo/net/layout-radial-expand.html
  site/zh-cn/g6/3.x/demo/net/layout-subgraph.html
  site/zh-cn/g6/3.x/demo/net/layout-timing.html
  site/zh-cn/g6/3.x/demo/net/node-flow.html
  site/zh-cn/g6/3.x/demo/scatter/hover-animate.html
  site/zh-cn/g6/3.x/demo/scatter/node-animate.html
  site/zh-cn/g6/3.x/demo/shape/area-chart-node.html
  site/zh-cn/g6/3.x/demo/shape/bar-chart-node.html
  site/zh-cn/g6/3.x/demo/shape/cardNode.html
  site/zh-cn/g6/3.x/demo/shape/cubic-horiontal.html
  site/zh-cn/g6/3.x/demo/shape/default-shapes.html
  site/zh-cn/g6/3.x/demo/shape/line-chart-node.html
  site/zh-cn/g6/3.x/demo/shape/listNode.html
  site/zh-cn/g6/3.x/demo/shape/multiple-edge-label.html
  site/zh-cn/g6/3.x/demo/shape/multiple-node-lable.html
  site/zh-cn/g6/3.x/demo/shape/pieNode.html
  site/zh-cn/g6/3.x/demo/shape/point-chart-node.html
  site/zh-cn/g6/3.x/demo/shape/polyline.html
  site/zh-cn/g6/3.x/demo/shape/register-arrow.html
  site/zh-cn/g6/3.x/demo/shape/register-polyline.html
  site/zh-cn/g6/3.x/demo/shape/stacked-bar-chart-node.html
  site/zh-cn/g6/3.x/demo/shape/text-ellipse.html
  site/zh-cn/g6/3.x/demo/shape/text-wrap.html
  site/zh-cn/g6/3.x/demo/tool/context-menu.html
  site/zh-cn/g6/3.x/demo/tool/edge-bundling.html
  site/zh-cn/g6/3.x/demo/tool/focus-center.html
  site/zh-cn/g6/3.x/demo/tool/sub-event.html
  site/zh-cn/g6/3.x/demo/tree/cloudatlas-tree.html
  site/zh-cn/g6/3.x/demo/tree/custom-tree.html
  site/zh-cn/g6/3.x/demo/tree/tree-indented.html
  theme/default/templates/demos.html
Labels: PR: reviewed-changes-requested, bug

#212 add: link to lark on the homepage; add: g6 demos;
  site-config.js
  site/zh-cn/g6/3.x/demo/interaction/hover-change-label.html
  site/zh-cn/g6/3.x/demo/shape/arc.html
  site/zh-cn/g6/3.x/demo/shape/arrow-config.html
  site/zh-cn/g6/3.x/demo/shape/default-shapes.html
  site/zh-cn/g6/3.x/demo/shape/internal-edges.html
  site/zh-cn/g6/3.x/demo/shape/internal-nodes.html
  site/zh-cn/g6/3.x/demo/shape/polyline.html
  site/zh-cn/g6/3.x/demo/shape/register-arrow.html
  site/zh-cn/g6/3.x/demo/shape/register-polyline1.html
  site/zh-cn/g6/3.x/demo/shape/register-polyline2.html
  site/zh-cn/g6/3.x/demo/shape/text-ellipse.html
  site/zh-cn/g6/3.x/demo/shape/text-wrap.html
  theme/default/src/Home/VideoBanner.jsx
  theme/default/src/Home/home.index.less
Labels: PR: unreviewed, add

#213 更新 F2 版本号
  site-config.js
Labels: PR: reviewed-changes-requested

#214 fix: lark link to new label page
  theme/default/src/Home/VideoBanner.jsx
Labels: PR: unreviewed, bug
